// Generated by CoffeeScript 1.6.2
(function() {
  define(["when", "moduleHash"], function(WhenP, moduleHash) {
    var isFooterHash;

    isFooterHash = false;
    // window.location.href = "/tests/#!/header";
    return describe("an async spec - header", function() {
      var async;

      async = new AsyncSpec(this);
      async.afterEach(function(done) {
        var hash,
          _this = this;

        hash = window.location.hash;
        if (hash.indexOf("!/header") > 0) {
          setTimeout(function() {
            return window.location.href = "/tests/#!/footer";
          }, 1000);
          console.log("redirect to ", window.location.href);
        }
        return done();
      });
      return async.it("load header", function(done) {
        var proms;

        proms = [];
        proms.push(moduleHash.getModuleAsPromise("header"));
        proms.push(moduleHash.getModuleAsPromise("footer"));
        return WhenP.all(proms);
      });
    });
  });

}).call(this);
